import { personal, payment, subscription } from "../../Shared/ProductInfo";

export const initialValues = {
  type: "WEIGHT",
  personal,
  payment,
  subscription,
  measurement: {
    feet: "5",
    inches: "0",
    currentWeight: 0,
    goalWeight: 0,
    heaviestWeight: 0,
    heaviestWeightAge: 0,
    lowestWeight: 0,
    lowestWeightAge: 0,
  },
  medicalHistory: {
    hypertension: false,
    hypertensionExplain: "",
    heartFailure: false,
    heartFailureExplain: "",
    heartAttack: false,
    heartAttackExplain: "",
    cardiacArrhythmias: false,
    cardiacArrhythmiasExplain: "",
    stroke: false,
    strokeExplain: "",
    thyroidDisease: false,
    thyroidDiseaseExplain: "",
    lungProblems: false,
    lungProblemsExplain: "",
    pulmonaryHypertension: false,
    pulmonaryHypertensionExplain: "",
    diabetes: false,
    diabetesExplain: "",
    parkinsons: false,
    parkinsonsExplain: "",
    anemia: false,
    anemiaExplain: "",
    heartburn: false,
    heartburnExplain: "",
    arthritis: false,
    arthritisExplain: "",
    sexualDysfunction: false,
    sexualDysfunctionExplain: "",
    fibromyalgia: false,
    fibromyalgiaExplain: "",
    depression: false,
    depressionExplain: "",
    seizures: false,
    seizuresExplain: "",
    menopause: false,
    menopauseExplain: "",
    bloodDonations: false,
    bloodDonationsExplain: "",
    lupus: false,
    lupusExplain: "",
    cancer: false,
    cancerExplain: "",
    congestion: false,
    congestionExplain: "",
    kidneyDisease: false,
    kidneyDiseaseExplain: "",
  },
  surgeries: {
    answer: "",
    explain: "",
  },
  familyHistory: {
    heartDisease: false,
    diabetes: false,
    cholesterol: false,
    thyroid: false,
    none: false,
  },
  noseIssues: {
    none: false,
  },
  noseCongested: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  noseClearMucus: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  noseColoredMucus: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  noseItchy: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  noseSmell: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  noseSnoring: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  noseSneezing: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  eyeIssues: {
    none: false,
  },
  eyeWatery: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  eyeItchy: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  eyeRed: {
    selected: false,
    frequency: "",
    side: "",
  },
  eyeDry: {
    selected: false,
    side: "",
    frequency: "frequency",
    occurs: "occurs",
  },
  eyeSwollen: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  eyeDischarge: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  earIssues: {
    none: false,
  },
  earClogged: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  earItchy: {
    selected: false,
    side: "",
    frequency: "",
    occurs: "",
  },
  earRinging: {
    selected: false,
    frequency: "",
    side: "",
  },
  earHearingLoss: {
    selected: false,
    side: "",
    frequency: "",
  },
  throatIssues: {
    none: false,
  },
  throatSore: {
    selected: false,
    frequency: "",
    occurs: "",
  },
  throatCough: {
    selected: false,
    frequency: "",
    occurs: "",
  },
  throatItchy: {
    selected: false,
    frequency: "",
    occurs: "",
  },
  throatClearing: {
    selected: false,
    frequency: "",
    occurs: "",
  },
  throatHoarse: {
    selected: false,
    frequency: "",
    occurs: "",
  },
  throatPostNasal: {
    selected: false,
    frequency: "",
    occurs: "",
  },
  headIssues: {
    none: false,
  },
  headAche: {
    selected: false,
    frequency: "",
  },
  headPressure: {
    frequency: "",
  },
  otherMedicines: {
    taking: "",
    explain: "",
  },
  symptomsBegan: {
    answer: "",
  },
  symptomMonths: {
    have: "",
    severe: "",
  },
  infectionsPerYear: {
    answer: "",
  },
  makeWorse: {
    irritants: [],
    medicine: [],
    allergens: [],
    location: [],
  },
  dwelling: {
    location: "",
    locationother: "",
    type: "",
    typeother: "",
  },
  hasSmoked: {
    selected: false,
    howMuch: "",
    hasQuit: "",
  },
  hasPets: {
    selected: false,
  },
  allergyMeds: {
    allegra: false,
    benedryl: false,
    claritin: false,
    flonase: false,
    phenylephrine: false,
    sudafed: false,
    zyrtec: false,
    other: false,
    otherExplain: "",
    none: false,
  },
  problems: {
    earInfections: false,
    sinus: false,
    brokenNose: false,
    earTubes: false,
    nasalSurgery: false,
    nasalPolyps: false,
    deviatedSeptum: false,
    none: false,
  },
  skinTesting: {
    answer: "",
    explain: "",
  },
  shots: {
    answer: "",
    range1: {
      from: "",
      to: "",
    },
    range2: {
      from: "",
      to: "",
    },
    range3: {
      from: "",
      to: "",
    },
    helpful: "",
    reactions: "",
  },
  environment: {
    occupation: "",
    heating: "",
    airConditioning: "",
    bedroomFloor: "",
    familyRoomFloor: "",
    mattress: "",
    pillow: "",
    comforter: "",
  },
  dustCover: {
    selected: "",
    covered: [],
  },
  mold: {
    selected: "",
    problem: "",
    where: [],
  },
  anythingElse: {
    answer: "",
    explain: "",
  },
};
