import { personal, payment, subscription } from "../../Shared/ProductInfo";

export const initialValues = {
  type: "JOY",
  personal,
  payment,
  subscription,
  anythingElse: {
    answer: "",
    explain: "",
  },
  socialFactors: {
    lgbqt: false,
    alcohol: false,
    relationship: false,
    financial: false,
    job: false,
    divorce: false,
    death: false,
    children: false,
    postpartum: false,
    other: false,
    otherExplain: "",
  },
  howOften: {
    down: "",
    concentrating: "",
    pleasure: "",
    decisions: "",
    sad: "",
    agitated: "",
    fatigued: "",
    effort: "",
    failure: "",
    sleeping: "",
    kill: "",
    trapped: "",
    goodThings: "",
    weight: "",
    nervous: "",
    annoyed: "",
    afraid: "",
  },
  treatment: {
    answer: "",
    diagnosis: "",
    medication: "",
    medicationExplain: "",
    medicationHelpful: "",
    therapy: "",
    therapyHelpful: "",
  },
  vitaminD: {
    answer: "",
    supplement: "",
  },
  childhood: {
    answer: "",
  },
};
